apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: {{.Env.SERVICE_API_IMAGE_NAME}}
          ports:
            - containerPort: 3100
          envFrom:
          - secretRef:
              name: todo-api-secret
          env:
            - name: AZURE_CLIENT_ID
              value: {{.Env.AZURE_AKS_IDENTITY_CLIENT_ID}}
          volumeMounts:
            - name: config-volume
              mountPath: /app/configDir
      volumes:
        - name: config-volume
          configMap:
            name: todo-api-config
            items:
              - key: default.json
                path: default.json
